
from os import path
from os import utime
from shutil import move


"""
Helper functions for creating callfiles and managing Asterisk.

"""
__author__ = 'Justin Zimmer'



def file_innards(config, call):
    """Generate Asterisk Call File in /tmp/, set mod time, and mv to spool path."""
    call_file = """
CallerID: {0}
Channel: Local/{1}@carriervmagi
Extension: {2}@vmdropagi 
Set: vm_file={3},vm_number={2},campaign={4},dial_id={5}
""".format(
    config["ani"],
    call.access_number,
    call.vm_number.national_number,
    config["vm_file"], config["campaign"],
    call.dialstatus.dial_id)
    return call_file


def schedule_call(call_file, config, call, call_epoch):
    """
    Write Asterisk Call File in /tmp/, set mod time, and mv to spool path.
    call_file must be generated by file_innards before calling schedule.
    call_time must be a UNIX timestamp generated by Schedule..
    """

    filename = "{0}_{1}_{2}.call".format(
        config["campaign"],
        call.vm_number.national_number,
        call_epoch)
    temp_file = "/tmp/{0}".format(filename)
    spool_file = config["ast_spool"]+"/"+filename
    handle = open(temp_file, "w")
    handle.write(call_file)
    handle.close()
    utime(temp_file, (call_epoch, call_epoch))
    move(temp_file, spool_file)
    return spool_file







